server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: apigatewayservice
  security:
    oauth2:
      client:
        provider:
          api-keycloak-provider:
            issuer-uri: http://localhost:8081/realms/fda
        registration:
          api-gateway-service:
            provider: api-keycloak-provider
            client-id: fda-gateway
            client-secret: 51XXY31JuYxnd9l73AiT6nJUgo1X6aYX
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri=http: //localhost:8080/login/oauth2/code/keycloak
  cloud:    
    gateway:      
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
      routes:
        - id: mscatalog
          uri: lb://api-catalog
          predicates:
            - Path=/api/v1/catalog/**

        
info:
  app:
    name: ${spring.application.name}

eureka:
   client:
      registerWithEureka: false
      fetchRegistry: true
      serviceURL:
         defaultZone: http://localhost:8761/eureka
management:
   endpoint:
      gateway:
         enabled: true
   endpoints:
      web:
         exposure:
            include: gateway
